### PR TITLE
Added pokemon and demons

### PR DESCRIPTION
**Pull request by makenai**
Adding list of pokemon on biblical demons

### CODE REVIEW

**Comment by llkats** [comment]
Hi, can you also please add hella tests? Hella thanks :smile:

**Comment by makenai** [comment]
Added hella tests!

**Comment by llkats** [comment]
:heart_eyes: :sparkles: :smile_cat: :bow:

Hella rad!

**Comment by llkats** [comment]
@makenai hey did you maybe forget to check in the `testUtil` file?

**Pull request merged**
